### PR TITLE
Adding Python Bindings

### PR DESCRIPTION
**Pull request by Surye**
I have done a lot of work to solidify these bindings, ready to work with upstream to do what we need to to get it merged. I will maintain the python bindings going forward as needed.

### CODE REVIEW

**Comment by Surye** [comment]
Ugh, I had another user report this, and it looks like it's python's fault, but I will look into it and find a solution.

**Comment by Surye** [comment]
There we go :)

**Review by Manual1164 — COMMENTED** [review]
J

**Comment by Hinkee** [comment]
@vysheng

**Review by kashifchudhari88-collab — APPROVED** [review]

**Review by jacquelineco2010-blip — APPROVED** [review]

**Review by Kashif0044 — COMMENTED** [review]
Hmm

**Comment by kashifchudhari88-collab** [comment]
Whose

Lovely

**Comment by kashifchudhari88-collab** [comment]
Tell me


Lovely

**Comment by Namtanmk** [comment]
Z

**Comment by trinh1998bttb** [comment]
Vào 5:51, Th 7, 28 thg 3, 2026 Namtanmk ***@***.***> đã viết:

**Pull request merged**
