### PR TITLE
[commands] added optional status to ```send_typing``` command.

### PR DESCRIPTION
**Pull request by luckydonald**
Update of pull request #413 and issue #340

### CODE REVIEW

**Comment by luckydonald** [comment]
The used regex, btw:
```regex
^\s*\{"(.*?)", \{((?:ca_(?:[a-z_A-Z]+)(?:(?:,|\s+\|)\s+)?)+)\},\s+[a-z_A-Z]+,\s+"\1\s*(.*)\\t(.+?)",\s+NULL}(,?)
```

**Comment by rnhmjoj** [comment]
There are some problems I've found with this command:
Option 0 sends "typing..." too. What should `none` do? Is it right?
Options 4, 6, 7 and 8 all fail with `FAIL: 71: RPC_CALL_FAIL 400: INPUT_FETCH_ERROR`
Also every status lasts only a couple of seconds. Shouldn't the status be kept until one issue the `send_typing_abort` command?

**Comment by luckydonald** [comment]
>Also every status lasts only a couple of seconds. Shouldn't the status be kept until one issue the ```send_typing_abort``` command?    

That's a design decision I guess.
[issue #340, comment 5](https://github.com/vysheng/tg/issues/340#issuecomment-66859485)

As for the crash, that might be a recent change in the code I violated to add this support :smile:  
That said, I have no time this week to check that (exams 'n' stuff...).
Maybe you should file a new issue for that.

**Comment by luckydonald** [comment]
@rnhmjoj  If you do, please add a link here, please.

**Pull request merged**
