### PR TITLE
Messages outputs in JSON format when client is started with -J param

### PR DESCRIPTION
**Pull request by andmart**
I'm using telegram-cli for a particular project and I found tricky to parse its output even with colors disabled. So, I created a JSON mode to output messages in this format.
The keys are datetime, chat, user and text.

Example;
{"datetime"="2015/04/10 23:37:32",  "chat"="Ingress chat", "user"="Fulano", "text"="Go, Enlightened"}

### CODE REVIEW

**Comment by lukefx** [comment]
Hey! I would love this feature, but your example output is not valid json, should be something like:

```
{"datetime":"2015/04/10 23:37:32", "chat":"Ingress chat", "user":"Fulano", "text":"Go, Enlightened"}
```

**Comment by andmart** [comment]
You are right. I've changed dict [key, value] separator from = to :.  
I added "fwd" key with original user id for forwarded messages too. 
Thanks for your observation.

**Comment by lukefx** [comment]
I love this feature! Should be merged immediately! I'm already using it and it's a super time saving for parsing messages :+1: Kudos to @andmart for the great work

**Comment by zqsd** [comment]
That's a great idea, but I've found that message strings are not escaped :

    {"datetime":"2015/04/13 10:55:24",  "user":"Clément "zqsd" Wiz", "text":"Resistance is "futile""}

**Comment by phoudoin** [comment]
Maybe JSON format should be in fact the internal format, and the cli should print it in user friendly form, except when -J option is specified?

May I recommand Jansson (http://www.digip.org/jansson/) to avoid to do escaping, encoding, formating & co again yourself?

**Comment by jonnywilliamson** [comment]
This would be brilliant. Making sure the json is escaped properly is very important though! Hopefully will get implemented soon when mr @vysheng gets back next week :)

Thanks.

**Comment by phoudoin** [comment]
Only text content is now escaped, while recipent (group or user, whatever) should be *too*,or JSON can still be invalid in some cases.

**Comment by luckydonald** [comment]
```-J``` as alias of ```--json``` would make sense.

**Comment by jonnywilliamson** [comment]
@luckydonald Thank you for these!

I sent you an email, please let me know if I got the wrong address. Cheers

**Comment by luckydonald** [comment]
@jonnywilliamson: Huh?
I have no idea to which of my many addresses you sent. 
Please contact me on telegram. Just search for @luckydonald

**Comment by luckydonald** [comment]
maybe @andmart should close this, as it is implemented now.

**Pull request closed without merging**
